### ISSUE TITLE
Compatibility issues errors and also missing other needed objects

### ISSUE THREAD

**Issue by weedkiller** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-DotNet#10]
Hi this is a good start, only because its deeper than the others. Since, this is the only ASP MVC C# sample (wish you had more), so we are using this as an example to build out other use cases, but running into the following issues.

- [ ] I wanted to report that we need more native Intuit or QB objects, so we can pick and choose which ones we populate and send (besides the time objects, _we have other use cases_.)
- [ ] Please maintain DAL access list of objects that we can access from the installed desktop version.
- [ ] Please maintain the level of inter operabilty and versioning, I cannot get one consistent C# Interface to work with different versions of the Desk Top versions!

when i was using 3rd party components they were easier and more consistent!!

**Comment by nimisha84** [comment]
Unfortunately this sample app works only for Online. In fact all the sample apps here are for QBO only.
Please look into the Desktop docs on developer.intuit.com to get the details you need for desktop.
Raise any queries you have on https://developer.intuit.com/ ->Help
