### ISSUE TITLE
Need a version that works with MVC 5 ASP Identity  2.2

### ISSUE THREAD

**Issue by weedkiller** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-DotNet#11]
Hi, since the time tracking application is user based and all the ASP MVC applications are using ASP Identity V2.2, we need a time tracking version 

for e.g. **where the user table in ASP Identity is one object, and then the Quickbooks user object and company objects are different - trying to sync the two users on the fly** has failed sending data in many cases.

This is a very common scenario, please address this

thanks

**Comment by nimisha84** [comment]
I do not believe that there will be a diff in case of QBO as we use Oauth1.
For desktop this might be true but not for QBO.
You can see this sample app from our external developers using ASP identity which he sync/creates only after OAuth is done. https://github.com/oflahero/QuickBooksAppMVC5

**Comment by weedkiller** [comment]
Hi, you misread my question...

Its not about Oauth, but to have a user - correctly mapped to the Quickbooks user object...
many of your samples/objects are so poorly conceived that your own online, desktop version implemented do not properly match!!

**Comment by IntuitDeveloperRelations** [comment]
Users of an application are not mapped to the users of QuickBooks.

**Comment by nimisha84** [comment]
The desktop and QBO are different products and there is no correlation as to how to map all the properties of QBD to QBO. The API is not exactly the same as xml based Desktop model.
(I will not be replying here as this is not the right forum for discussion. )Please post your question on developer.intuit.com->Help going forward.

**Comment by weedkiller** [comment]
We only support the community, many of these issues are slowly causing people to migrate to other software options!

**Comment by nimisha84** [comment]
HI WeedKiller, 

Please share your contact info so that I can discuss this on a meeting with you.

Thanks!
